// Code generated by counterfeiter. DO NOT EDIT.
package repositoryfakes

import (
	"context"
	"sync"

	"github.com/kava-forge/eve-alts/pkg/database"
	"github.com/kava-forge/eve-alts/pkg/repository"
	"github.com/kava-forge/eve-alts/pkg/repository/internal/static"
)

type FakeStaticData struct {
	BatchGetSkillNamesStub        func(context.Context, []int64, database.Tx) ([]static.BatchGetSkillNamesRow, error)
	batchGetSkillNamesMutex       sync.RWMutex
	batchGetSkillNamesArgsForCall []struct {
		arg1 context.Context
		arg2 []int64
		arg3 database.Tx
	}
	batchGetSkillNamesReturns struct {
		result1 []static.BatchGetSkillNamesRow
		result2 error
	}
	batchGetSkillNamesReturnsOnCall map[int]struct {
		result1 []static.BatchGetSkillNamesRow
		result2 error
	}
	CleanTranslationsStub        func(context.Context, database.Tx) error
	cleanTranslationsMutex       sync.RWMutex
	cleanTranslationsArgsForCall []struct {
		arg1 context.Context
		arg2 database.Tx
	}
	cleanTranslationsReturns struct {
		result1 error
	}
	cleanTranslationsReturnsOnCall map[int]struct {
		result1 error
	}
	GetSkillIDByNameStub        func(context.Context, string, database.Tx) (int64, error)
	getSkillIDByNameMutex       sync.RWMutex
	getSkillIDByNameArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 database.Tx
	}
	getSkillIDByNameReturns struct {
		result1 int64
		result2 error
	}
	getSkillIDByNameReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	GetSkillNameStub        func(context.Context, int64, database.Tx) (string, error)
	getSkillNameMutex       sync.RWMutex
	getSkillNameArgsForCall []struct {
		arg1 context.Context
		arg2 int64
		arg3 database.Tx
	}
	getSkillNameReturns struct {
		result1 string
		result2 error
	}
	getSkillNameReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetTableNamesStub        func(context.Context, database.Tx) ([]string, error)
	getTableNamesMutex       sync.RWMutex
	getTableNamesArgsForCall []struct {
		arg1 context.Context
		arg2 database.Tx
	}
	getTableNamesReturns struct {
		result1 []string
		result2 error
	}
	getTableNamesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStaticData) BatchGetSkillNames(arg1 context.Context, arg2 []int64, arg3 database.Tx) ([]static.BatchGetSkillNamesRow, error) {
	var arg2Copy []int64
	if arg2 != nil {
		arg2Copy = make([]int64, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.batchGetSkillNamesMutex.Lock()
	ret, specificReturn := fake.batchGetSkillNamesReturnsOnCall[len(fake.batchGetSkillNamesArgsForCall)]
	fake.batchGetSkillNamesArgsForCall = append(fake.batchGetSkillNamesArgsForCall, struct {
		arg1 context.Context
		arg2 []int64
		arg3 database.Tx
	}{arg1, arg2Copy, arg3})
	stub := fake.BatchGetSkillNamesStub
	fakeReturns := fake.batchGetSkillNamesReturns
	fake.recordInvocation("BatchGetSkillNames", []interface{}{arg1, arg2Copy, arg3})
	fake.batchGetSkillNamesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStaticData) BatchGetSkillNamesCallCount() int {
	fake.batchGetSkillNamesMutex.RLock()
	defer fake.batchGetSkillNamesMutex.RUnlock()
	return len(fake.batchGetSkillNamesArgsForCall)
}

func (fake *FakeStaticData) BatchGetSkillNamesCalls(stub func(context.Context, []int64, database.Tx) ([]static.BatchGetSkillNamesRow, error)) {
	fake.batchGetSkillNamesMutex.Lock()
	defer fake.batchGetSkillNamesMutex.Unlock()
	fake.BatchGetSkillNamesStub = stub
}

func (fake *FakeStaticData) BatchGetSkillNamesArgsForCall(i int) (context.Context, []int64, database.Tx) {
	fake.batchGetSkillNamesMutex.RLock()
	defer fake.batchGetSkillNamesMutex.RUnlock()
	argsForCall := fake.batchGetSkillNamesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStaticData) BatchGetSkillNamesReturns(result1 []static.BatchGetSkillNamesRow, result2 error) {
	fake.batchGetSkillNamesMutex.Lock()
	defer fake.batchGetSkillNamesMutex.Unlock()
	fake.BatchGetSkillNamesStub = nil
	fake.batchGetSkillNamesReturns = struct {
		result1 []static.BatchGetSkillNamesRow
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) BatchGetSkillNamesReturnsOnCall(i int, result1 []static.BatchGetSkillNamesRow, result2 error) {
	fake.batchGetSkillNamesMutex.Lock()
	defer fake.batchGetSkillNamesMutex.Unlock()
	fake.BatchGetSkillNamesStub = nil
	if fake.batchGetSkillNamesReturnsOnCall == nil {
		fake.batchGetSkillNamesReturnsOnCall = make(map[int]struct {
			result1 []static.BatchGetSkillNamesRow
			result2 error
		})
	}
	fake.batchGetSkillNamesReturnsOnCall[i] = struct {
		result1 []static.BatchGetSkillNamesRow
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) CleanTranslations(arg1 context.Context, arg2 database.Tx) error {
	fake.cleanTranslationsMutex.Lock()
	ret, specificReturn := fake.cleanTranslationsReturnsOnCall[len(fake.cleanTranslationsArgsForCall)]
	fake.cleanTranslationsArgsForCall = append(fake.cleanTranslationsArgsForCall, struct {
		arg1 context.Context
		arg2 database.Tx
	}{arg1, arg2})
	stub := fake.CleanTranslationsStub
	fakeReturns := fake.cleanTranslationsReturns
	fake.recordInvocation("CleanTranslations", []interface{}{arg1, arg2})
	fake.cleanTranslationsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeStaticData) CleanTranslationsCallCount() int {
	fake.cleanTranslationsMutex.RLock()
	defer fake.cleanTranslationsMutex.RUnlock()
	return len(fake.cleanTranslationsArgsForCall)
}

func (fake *FakeStaticData) CleanTranslationsCalls(stub func(context.Context, database.Tx) error) {
	fake.cleanTranslationsMutex.Lock()
	defer fake.cleanTranslationsMutex.Unlock()
	fake.CleanTranslationsStub = stub
}

func (fake *FakeStaticData) CleanTranslationsArgsForCall(i int) (context.Context, database.Tx) {
	fake.cleanTranslationsMutex.RLock()
	defer fake.cleanTranslationsMutex.RUnlock()
	argsForCall := fake.cleanTranslationsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStaticData) CleanTranslationsReturns(result1 error) {
	fake.cleanTranslationsMutex.Lock()
	defer fake.cleanTranslationsMutex.Unlock()
	fake.CleanTranslationsStub = nil
	fake.cleanTranslationsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStaticData) CleanTranslationsReturnsOnCall(i int, result1 error) {
	fake.cleanTranslationsMutex.Lock()
	defer fake.cleanTranslationsMutex.Unlock()
	fake.CleanTranslationsStub = nil
	if fake.cleanTranslationsReturnsOnCall == nil {
		fake.cleanTranslationsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.cleanTranslationsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStaticData) GetSkillIDByName(arg1 context.Context, arg2 string, arg3 database.Tx) (int64, error) {
	fake.getSkillIDByNameMutex.Lock()
	ret, specificReturn := fake.getSkillIDByNameReturnsOnCall[len(fake.getSkillIDByNameArgsForCall)]
	fake.getSkillIDByNameArgsForCall = append(fake.getSkillIDByNameArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 database.Tx
	}{arg1, arg2, arg3})
	stub := fake.GetSkillIDByNameStub
	fakeReturns := fake.getSkillIDByNameReturns
	fake.recordInvocation("GetSkillIDByName", []interface{}{arg1, arg2, arg3})
	fake.getSkillIDByNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStaticData) GetSkillIDByNameCallCount() int {
	fake.getSkillIDByNameMutex.RLock()
	defer fake.getSkillIDByNameMutex.RUnlock()
	return len(fake.getSkillIDByNameArgsForCall)
}

func (fake *FakeStaticData) GetSkillIDByNameCalls(stub func(context.Context, string, database.Tx) (int64, error)) {
	fake.getSkillIDByNameMutex.Lock()
	defer fake.getSkillIDByNameMutex.Unlock()
	fake.GetSkillIDByNameStub = stub
}

func (fake *FakeStaticData) GetSkillIDByNameArgsForCall(i int) (context.Context, string, database.Tx) {
	fake.getSkillIDByNameMutex.RLock()
	defer fake.getSkillIDByNameMutex.RUnlock()
	argsForCall := fake.getSkillIDByNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStaticData) GetSkillIDByNameReturns(result1 int64, result2 error) {
	fake.getSkillIDByNameMutex.Lock()
	defer fake.getSkillIDByNameMutex.Unlock()
	fake.GetSkillIDByNameStub = nil
	fake.getSkillIDByNameReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) GetSkillIDByNameReturnsOnCall(i int, result1 int64, result2 error) {
	fake.getSkillIDByNameMutex.Lock()
	defer fake.getSkillIDByNameMutex.Unlock()
	fake.GetSkillIDByNameStub = nil
	if fake.getSkillIDByNameReturnsOnCall == nil {
		fake.getSkillIDByNameReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.getSkillIDByNameReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) GetSkillName(arg1 context.Context, arg2 int64, arg3 database.Tx) (string, error) {
	fake.getSkillNameMutex.Lock()
	ret, specificReturn := fake.getSkillNameReturnsOnCall[len(fake.getSkillNameArgsForCall)]
	fake.getSkillNameArgsForCall = append(fake.getSkillNameArgsForCall, struct {
		arg1 context.Context
		arg2 int64
		arg3 database.Tx
	}{arg1, arg2, arg3})
	stub := fake.GetSkillNameStub
	fakeReturns := fake.getSkillNameReturns
	fake.recordInvocation("GetSkillName", []interface{}{arg1, arg2, arg3})
	fake.getSkillNameMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStaticData) GetSkillNameCallCount() int {
	fake.getSkillNameMutex.RLock()
	defer fake.getSkillNameMutex.RUnlock()
	return len(fake.getSkillNameArgsForCall)
}

func (fake *FakeStaticData) GetSkillNameCalls(stub func(context.Context, int64, database.Tx) (string, error)) {
	fake.getSkillNameMutex.Lock()
	defer fake.getSkillNameMutex.Unlock()
	fake.GetSkillNameStub = stub
}

func (fake *FakeStaticData) GetSkillNameArgsForCall(i int) (context.Context, int64, database.Tx) {
	fake.getSkillNameMutex.RLock()
	defer fake.getSkillNameMutex.RUnlock()
	argsForCall := fake.getSkillNameArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeStaticData) GetSkillNameReturns(result1 string, result2 error) {
	fake.getSkillNameMutex.Lock()
	defer fake.getSkillNameMutex.Unlock()
	fake.GetSkillNameStub = nil
	fake.getSkillNameReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) GetSkillNameReturnsOnCall(i int, result1 string, result2 error) {
	fake.getSkillNameMutex.Lock()
	defer fake.getSkillNameMutex.Unlock()
	fake.GetSkillNameStub = nil
	if fake.getSkillNameReturnsOnCall == nil {
		fake.getSkillNameReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getSkillNameReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) GetTableNames(arg1 context.Context, arg2 database.Tx) ([]string, error) {
	fake.getTableNamesMutex.Lock()
	ret, specificReturn := fake.getTableNamesReturnsOnCall[len(fake.getTableNamesArgsForCall)]
	fake.getTableNamesArgsForCall = append(fake.getTableNamesArgsForCall, struct {
		arg1 context.Context
		arg2 database.Tx
	}{arg1, arg2})
	stub := fake.GetTableNamesStub
	fakeReturns := fake.getTableNamesReturns
	fake.recordInvocation("GetTableNames", []interface{}{arg1, arg2})
	fake.getTableNamesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeStaticData) GetTableNamesCallCount() int {
	fake.getTableNamesMutex.RLock()
	defer fake.getTableNamesMutex.RUnlock()
	return len(fake.getTableNamesArgsForCall)
}

func (fake *FakeStaticData) GetTableNamesCalls(stub func(context.Context, database.Tx) ([]string, error)) {
	fake.getTableNamesMutex.Lock()
	defer fake.getTableNamesMutex.Unlock()
	fake.GetTableNamesStub = stub
}

func (fake *FakeStaticData) GetTableNamesArgsForCall(i int) (context.Context, database.Tx) {
	fake.getTableNamesMutex.RLock()
	defer fake.getTableNamesMutex.RUnlock()
	argsForCall := fake.getTableNamesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeStaticData) GetTableNamesReturns(result1 []string, result2 error) {
	fake.getTableNamesMutex.Lock()
	defer fake.getTableNamesMutex.Unlock()
	fake.GetTableNamesStub = nil
	fake.getTableNamesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) GetTableNamesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.getTableNamesMutex.Lock()
	defer fake.getTableNamesMutex.Unlock()
	fake.GetTableNamesStub = nil
	if fake.getTableNamesReturnsOnCall == nil {
		fake.getTableNamesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.getTableNamesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeStaticData) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.batchGetSkillNamesMutex.RLock()
	defer fake.batchGetSkillNamesMutex.RUnlock()
	fake.cleanTranslationsMutex.RLock()
	defer fake.cleanTranslationsMutex.RUnlock()
	fake.getSkillIDByNameMutex.RLock()
	defer fake.getSkillIDByNameMutex.RUnlock()
	fake.getSkillNameMutex.RLock()
	defer fake.getSkillNameMutex.RUnlock()
	fake.getTableNamesMutex.RLock()
	defer fake.getTableNamesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStaticData) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ repository.StaticData = new(FakeStaticData)
