// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package static

import (
	"context"
	"strings"
)

const batchGetSkillNames = `-- name: BatchGetSkillNames :many
;

SELECT
    "keyID" as skill_id,
    "text" as skill_name
FROM
    trnTranslations
WHERE
    "tcID" = 8
    AND "languageID" = ?1
    AND "keyID" IN (/*SLICE:skill_ids*/?)
`

type BatchGetSkillNamesParams struct {
	Language string
	SkillIds []int64
}

type BatchGetSkillNamesRow struct {
	SkillID   int64
	SkillName string
}

func (q *Queries) BatchGetSkillNames(ctx context.Context, db DBTX, arg BatchGetSkillNamesParams) ([]BatchGetSkillNamesRow, error) {
	query := batchGetSkillNames
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Language)
	if len(arg.SkillIds) > 0 {
		for _, v := range arg.SkillIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:skill_ids*/?", strings.Repeat(",?", len(arg.SkillIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:skill_ids*/?", "NULL", 1)
	}
	rows, err := db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetSkillNamesRow
	for rows.Next() {
		var i BatchGetSkillNamesRow
		if err := rows.Scan(&i.SkillID, &i.SkillName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillIDFromName = `-- name: GetSkillIDFromName :one
;

SELECT
    "keyID" as skill_id
FROM
    trnTranslations
WHERE
    "tcID" = 8
    AND "languageID" = ?1
    AND LOWER("text") = ?2
LIMIT 1
`

type GetSkillIDFromNameParams struct {
	Language       string
	SkillNameLower string
}

func (q *Queries) GetSkillIDFromName(ctx context.Context, db DBTX, arg GetSkillIDFromNameParams) (int64, error) {
	row := db.QueryRowContext(ctx, getSkillIDFromName, arg.Language, arg.SkillNameLower)
	var skill_id int64
	err := row.Scan(&skill_id)
	return skill_id, err
}

const getSkillName = `-- name: GetSkillName :one
SELECT
    "text" as skill_name
FROM
    trnTranslations
WHERE
    "tcID" = 8
    AND "keyID" = ?1
    AND "languageID" = ?2
`

type GetSkillNameParams struct {
	SkillID  int64
	Language string
}

func (q *Queries) GetSkillName(ctx context.Context, db DBTX, arg GetSkillNameParams) (string, error) {
	row := db.QueryRowContext(ctx, getSkillName, arg.SkillID, arg.Language)
	var skill_name string
	err := row.Scan(&skill_name)
	return skill_name, err
}
