// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: staticdata_clean.sql

package static

import (
	"context"
)

const cleanTranslations = `-- name: CleanTranslations :exec
DELETE FROM trnTranslations
WHERE "tcID" != 8
`

func (q *Queries) CleanTranslations(ctx context.Context, db DBTX) error {
	_, err := db.ExecContext(ctx, cleanTranslations)
	return err
}

const getTableNames = `-- name: GetTableNames :many
SELECT 
    "name"
FROM sqlite_master
WHERE
    "type" = 'table'
ORDER BY "name"
`

func (q *Queries) GetTableNames(ctx context.Context, db DBTX) ([]string, error) {
	rows, err := db.QueryContext(ctx, getTableNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
