// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package staticdb

import (
	"database/sql"
)

type SqliteMaster struct {
	Type     sql.NullString
	Name     string
	TblName  sql.NullString
	Rootpage sql.NullInt64
	Sql      sql.NullString
}

type TrnTranslation struct {
	TcID       int64
	KeyID      int64
	LanguageID string
	Text       string
}
