// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package staticdb

import (
	"context"
)

type Querier interface {
	BatchGetSkillNames(ctx context.Context, db DBTX, arg BatchGetSkillNamesParams) ([]BatchGetSkillNamesRow, error)
	CleanTranslations(ctx context.Context, db DBTX) error
	GetSkillIDFromName(ctx context.Context, db DBTX, arg GetSkillIDFromNameParams) (int64, error)
	GetSkillName(ctx context.Context, db DBTX, arg GetSkillNameParams) (string, error)
	GetTableNames(ctx context.Context, db DBTX) ([]string, error)
}

var _ Querier = (*Queries)(nil)
